# Generated by Django 3.0 on 2022-08-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="letting",
                    name="address",
                ),
                migrations.RemoveField(
                    model_name="profile",
                    name="user",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Profile", table="profiles_profile"),
                migrations.AlterModelTable(name="Address", table="lettings_address"),
                migrations.AlterModelTable(name="Letting", table="lettings_letting"),
            ],
        ),
    ]
